# root-sync.yaml

apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  name: root-sync
  namespace: config-management-system
spec:
  sourceFormat: unstructured
  git:
    repo: git@github.com:nardosm/config-connector-poc.git
    branch: main
    auth: ssh
    secretRef:
      name: git-creds
